### PR TITLE
temp: try to change auth token from bearer to bearer jwt

### PR DESCRIPTION
**Pull request by mariajgrimaldi**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
label: core contributor

**Comment by itsjeyd** [comment]
Thanks for the PR @mariajgrimaldi! Let us know when it's ready for review.

**Comment by Ian2012** [comment]
@itsjeyd After further research we found out that we had to modify the SupersetSecurityManager subclass to add support for `jwt` 
change the scope and send an extra param called `token_type`.

It's ready for review

**Comment by bmtcril** [comment]
Is this PR still relevant, or is it rolled into the other one?

**Comment by Ian2012** [comment]
It's not relevant anymore

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-superset&entry.867055334=https://github.com/openedx/tutor-contrib-superset/pull/40&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2023-05-18+19:24&entry.1917517419=2023-05-30+16:48&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
