### PR TITLE
refactor: use patch files instead

### PR DESCRIPTION
**Pull request by Ian2012**
## Description

This PR uses docker patches to improve readability

## Testing instructions

For testing you can configure a development environment using the following script:

```bash
virtualenv -p python3.8 venv && source venv/bin/activate
git clone --branch=nightly https://github.com/overhangio/tutor.git
pip install -e "./tutor[full]"
export TUTOR_PLUGINS_ROOT=$(pwd)/plugins/ export TUTOR_ROOT=$(pwd)
git clone https://github.com/openedx/tutor-contrib-oars
git clone https://github.com/openedx/tutor-contrib-ralph
git clone https://github.com/openedx/tutor-contrib-clickhouse
git clone https://github.com/openedx/tutor-contrib-superset
pip install -e ./tutor-contrib-clickhouse
pip install -e ./tutor-contrib-ralph
pip install -e ./tutor-contrib-oars
pip install -e ./tutor-contrib-superset
tutor plugins enable oars
tutor plugins enable ralph
tutor plugins enable clickhouse
tutor plugins enable superset
tutor config save
```

Then create a local git repository including all the changes. The following **.gitignore** can be used as a reference:

```
tutor-contrib-clickhouse
tutor-contrib-oars
tutor-contrib-ralph
tutor-contrib-superset
tutor
venv
data

**/k8s/jobs.yml
**/env/version
**/superset_home
venv/

__pycache__/
*.py[cod]
```

Then, you can review this branch and run tutor config save. The only difference should be in some blank characters but the overall result is the same.

The modified files should be:
- **env/dev/docker-compose.yml**
- **env/dev/docker-compose.jobs.yml**
- **env/local/docker-compose.yml**
- **env/local/docker-compose.jobs.yml**

## References

For reference, all official tutor plugins use files instead of patches programmatically:

https://github.com/overhangio/tutor-discovery/tree/master/tutordiscovery/patches
https://github.com/overhangio/tutor-notes/tree/master/tutornotes/patches
Among others

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Ian2012** [comment]
Even though there are more changes to apply to refactor this plugin, we will leave this PR as it is and in following PRs finish the work.

cc @bmtcril

**Comment by mariajgrimaldi** [comment]
Please, include some proof or some testing instructions to check that this is working as expected.

**Comment by mariajgrimaldi** [comment]
What's the plan for the initialization tasks?

**Comment by Ian2012** [comment]
Can those live on files too? @mariajgrimaldi

**Comment by mariajgrimaldi** [comment]
Oh no. I should've asked in another issue. But still, is there a plan for those?

**Comment by Ian2012** [comment]
This plugin should be able to run as an independent tutor plugin and for that it must comply with the ADR 006 which establishes the following responsibilities for superset:

- [ ] Create an admin user
- [ ] Create the Superset-specific MySQL database and permissions for the admin user (Note: By default this uses the LMS MySQL instance to save on system resources)
- [ ] Create a user in LMS for SSO
- [ ] Register itself as an SSO target with the LMS
- [ ] Disable local user management to force SSO login from LMS
- [ ] Create a set of default roles and permissions based on LMS permissions for each user (course staff, global staff, superuser, etc)
- [ ] Create row-based filters for queries to enforce course-level permissions (Note: since there are no datasets yet there is nothing to connect them to, but they are created here as they would likely be useful for a non-OARS use case)
- [ ] NOT create any ClickHouse databases, users, or tables.

The missing checks should be added to that improvement plan.

**Review by bmtcril — APPROVED** [review]
This looks good to me and worked for me locally, nice work!

**Comment by bmtcril** [comment]
@Ian2012 the row-based filters task is actually done, the call to create them is here: https://github.com/openedx/tutor-contrib-superset/blob/5d4f16c3a203d0235bd7e4dc3d68fbafa1765c05/tutorsuperset/templates/superset/jobs/init/init-superset.sh#L69

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-superset&entry.867055334=https://github.com/openedx/tutor-contrib-superset/pull/18&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-04-17+19:56&entry.1917517419=2023-04-18+13:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Ian2012** [comment]
@bmtcril Checking with my team, we found that this patch doesn't exist:

https://github.com/openedx/tutor-contrib-superset/pull/18/files#diff-34becf7bb60402c8556a9bc64d435f02a3c47ba1eb7c52606239bcc021c5dae6L281-L292

Did you mean https://docs.tutor.overhang.io/reference/patches.html#dev-docker-compose-jobs-services?

**Comment by pomegranited** [comment]
Ooo thank you for this @Ian2012 ! I didn't know what Tutor patch files were for. This makes the deployment much clearer!

**Pull request merged**
