### PR TITLE
feat: adds clickhouse-connect

### PR DESCRIPTION
**Pull request by pomegranited**
Adds `clickhouse-connect` python dependency so we can add Clickhouse as a data source.

Pins the version of `clickhouse-connect` to 0.5x, because they seem to make breaking changes with each minor release (cf https://github.com/openedx/xapi-db-load/pull/1#discussion_r1094599921).

**Dependencies**

* Setup requires https://github.com/openedx/tutor-contrib-clickhouse/pull/1

**Related discussions**

* Part of implementing https://github.com/openedx/openedx-oars/issues/30

**Testing instructions**

1. Follow [README](https://github.com/open-craft/tutor-contrib-superset#superset-plugin-for-tutor) to install this plugin.
2. Follow the testing instructions for [tutor-contrib-clickhouse#1](https://github.com/openedx/tutor-contrib-clickhouse/pull/1) to run that plugin too and load the demo xAPI data.
4. Login to [Superset](http://local.overhang.io:8088) via Open edX SSO as a superuser.
5. Add a new database connection to the `clickhouse_service:8123` using the `ch_report` credentials (ref [Superset: using Database Connections UI](https://superset.apache.org/docs/databases/db-connection-ui)):
  add_database
  clickhouse_connect
6. Add a new dataset for the `xapi.xapi_events_all` table (ref [Superset: Registering a new table](https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/#registering-a-new-table)).

### CODE REVIEW

**Comment by pomegranited** [comment]
Hi @bmtcril ! This one's really tiny, but ties together the other PRs you've reviewed.

I'll start adding the automation for setting up these datasets/dashboards with a PR against the new tutor-contrib-oars repo.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
Thank you for the update!

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-superset&entry.867055334=https://github.com/openedx/tutor-contrib-superset/pull/2&entry.1484655318=https://github.com/pomegranited&entry.752974735=2023-02-07+00:45&entry.1917517419=2023-02-21+14:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bmtcril** [comment]
I just merged this one since it's been hanging out, but you should be able to merge these yourself once it's reviewed. Let me know if you weren't able to do that and I'll look into it!

**Comment by pomegranited** [comment]
Thanks @bmtcril ! I was able to merge https://github.com/openedx/tutor-contrib-superset/pull/1, so I'm pretty sure I could have merged this too. Will let you know if that's not the case :)

**Pull request merged**
