### PR TITLE
fix: enable volumes for superset jobs

### PR DESCRIPTION
**Pull request by Ian2012**
## Description

This PR fixes an issue in which the superset job was unable to run because it doesn't had the necessary files.

It also adds support to integrate sentry with superset.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@Ian2012 Thank you for this contribution. Are the changes ready for review?

**Comment by Ian2012** [comment]
@itsjeyd It's ready for review. I've updated the PR description

**Review by bmtcril — APPROVED** [review]
Curious about the superset version change, but I think this is fine

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-superset&entry.867055334=https://github.com/openedx/tutor-contrib-superset/pull/27&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-04-26+22:40&entry.1917517419=2023-04-28+01:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Ian2012** [comment]
It was my mistake on another PR, so I was just reverting than change. Also, version 2.1.0 seems like a very breaking change, so let's keep that in mine for future work.

But, 2.1.0 has just been released son weeks ago, so nothing to worry about.

**Pull request merged**
